spring:
  datasource:
    url: jdbc:h2:mem:testdb  # H2 데이터베이스를 메모리 모드로 설정
    driver-class-name: org.h2.Driver  # H2 JDBC 드라이버
    username: sa  # 기본 사용자명
    password:     # 비밀번호는 비워 둠
  h2:
    console:
      enabled: true  # H2 웹 콘솔 활성화
      path: /h2-console  # H2 콘솔 경로 설정 (기본값은 /h2-console)
  jpa:
    hibernate:
      ddl-auto: update  # 스키마를 자동으로 업데이트
    show-sql: true  # SQL 쿼리를 콘솔에 출력
  data:
    redis:
      host: localhost
      port: 6379